name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'pages/**'
      - 'books/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      -       - name: Install Python, mkdocs, and mkdocs-material
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install mkdocs mkdocs-material

      - name: Build mkdocs site
        run: |
          cd books
          mkdocs build
          cd ..

      - name: Prepare combined _site output
        run: |
          mkdir -p ./_site
          cp -r pages/* ./_site/ || true
          cp -r books/site/* ./_site/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
