name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'pages/**'
      - 'books/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Install Python and mkdocs
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install mkdocs

      - name: Build mkdocs site for books
        run: |
          cd books
          mkdocs build -d ../_site/books
          cd ..

      - name: Copy pages to output
        run: |
          mkdir -p ./_site/pages
          cp -r pages/* ./_site/pages/ || true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
